### ISSUE TITLE
Share Subscription - Unable to remove current member

### ISSUE THREAD

**Issue by LISAANN9266** [mkoza178/Advance---MI-Merge#10]
When attempting to remove a current member from the shared subscriptions, an error appears.

![shareerror3](https://cloud.githubusercontent.com/assets/25617462/22941616/0f618d90-f29b-11e6-88e9-bfd0da1420e4.PNG)

**Comment by mkoza178** [comment]
TFS 34327

**Comment by LISAANN9266** [comment]
Able to remove a current member from share your subscription.
