### ISSUE TITLE
TFS 34379 Sign In button not working 

### ISSUE THREAD

**Issue by jvanzomeren** [mkoza178/Advance---MI-Merge#11]
https://test-member.mlive.com/Login.aspx?showlogin=true&siteCode=MI
![screen shot 2017-02-16 at 12 31 52 pm](https://cloud.githubusercontent.com/assets/25616598/23033292/81f5a9da-f445-11e6-8da4-2f4463a16117.png)

**Comment by mkoza178** [comment]
Hey Jon,

I'm unable to reproduce. Can you give me steps? Please include browser and desktop specs. Thanks!

**Comment by jvanzomeren** [comment]
so for whatever reason the gigya modal was not popping up and i just had the sign in button... all that said I cant reproduce it now either. working like a champ

**Comment by jvanzomeren** [comment]
Ok its doing it again to me.    it behaves like Gigya wont launch the modal and there is no hyperlink behind the Sign In Button.  Im using safari will try another browser.     Works fine in firefox...  clicking the Signing repopulates the modal

**Comment by mkoza178** [comment]
I'll test with safari as well.

**Comment by mkoza178** [comment]
I was able to reproduce in windows and mac on safari 5.1.7 (a very old browser)
I put a ticket in to see what we could do: TFS 34379

**Comment by mkoza178** [comment]
Jon,

The slideshow is now loading and we are able to see the modal appear but it doesn't fully render. My devs said this is out of their control and Gigya needs to review.

**Comment by jvanzomeren** [comment]
this is working now
