### ISSUE TITLE
TFS 34391 Ebill Sign up allowed for unpaid comps

### ISSUE THREAD

**Issue by jvanzomeren** [mkoza178/Advance---MI-Merge#12]
Should only be allowed for Office pay subs not on easy pay
![screen shot 2017-02-16 at 1 56 58 pm](https://cloud.githubusercontent.com/assets/25616598/23036184/d09230f4-f44f-11e6-9bc0-bdc4be6deb19.png)

**Comment by jvanzomeren** [comment]
login for this test was 
g2mitest+unpaid@gmail.com
test123

**Comment by mkoza178** [comment]
Hey Jon,

This user is a bill method = third party and according to the flowcharts they should not have access. I'll input a TFS.

**Comment by mkoza178** [comment]
TFS 34391

**Comment by mkoza178** [comment]
Resolved. Please verify

**Comment by jvanzomeren** [comment]
tested fine
