### ISSUE TITLE
SAG - not able to share subscription

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#13]
![sag_not able to share sub](https://cloud.githubusercontent.com/assets/25616655/23042703/9cb19cee-f467-11e6-9026-c8f3d1a1c0be.png)

**Comment by mkoza178** [comment]
Hm, not sure. Was not able to reproduce. Could you clear cache/cookies and try again?

**Comment by apattok** [comment]
working fine now...maybe just hosed the system with too many tests.
