### ISSUE TITLE
share subscription - wording confusing

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#14]
Says "Your Name"  "Your Email" but it's really the person you are sharing with, right?
![wording is confusing_share subscription](https://cloud.githubusercontent.com/assets/25616655/23042742/d2f503ea-f467-11e6-8d6d-f639d855a822.png)

**Comment by mkoza178** [comment]
Right, so would you want it to say "Enter first name", "Enter last name", "Enter email"?

**Comment by apattok** [comment]
Yes, that would work. I just think "your" is confusing...at least it was for me :)

**Comment by mkoza178** [comment]
TFS 34407

**Comment by mkoza178** [comment]
This looks good. Please verify!

**Comment by apattok** [comment]
verified - looks better!
