### ISSUE TITLE
FJNL Share Subscription_Error when clicking link in email

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#15]
Received invitation in email. Click the link and receive error:
![fjnl_share subscription_error when clicking on link to accept invite](https://cloud.githubusercontent.com/assets/25616655/23043704/22366db0-f46b-11e6-8668-d80f662ff606.png)

**Comment by mkoza178** [comment]
Updated text in email to point to the correct site. Try again!

**Comment by apattok** [comment]
Fix confirmed.
