### ISSUE TITLE
Nola - Vacation Package being displayed as vacation option

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#16]
In test, the option for the subscriber to select Vacation Package is displayed.  This is not displayed in production as New Orleans does not offer Vacation Pack.

**TEST**
![image](https://cloud.githubusercontent.com/assets/25667903/23043875/85f50a3a-f463-11e6-818c-f7277c85bb56.png)

**Production**
![image](https://cloud.githubusercontent.com/assets/25667903/23043902/a43912f2-f463-11e6-929e-bf5a2affaec2.png)

**Comment by mkoza178** [comment]
TFS 34399 created to remove it.

**Comment by mkoza178** [comment]
Removed. Please verify!
