### ISSUE TITLE
Share Subscription - Invitation removed or expired

### ISSUE THREAD

**Issue by LISAANN9266** [mkoza178/Advance---MI-Merge#17]
After submitting share subscription and receiving email, I clicked on the link and I get an error:  

**! THE INVITATION YOU ARE TRYING TO ACTIVATE WAS REMOVED OR HAS EXPIRED**

Invitation was from lstarkweconversion+mc3@gmail.com #152840

Invitations sent to lstarkweconversion+mc3a (mc3b, mc3c, mc3d) @gmail.com

This may be because I am sending to same email with extension????

**Comment by mkoza178** [comment]
I'm not sure the steps you took to get this error. Can you help me reproduce by giving me steps.

**Comment by LISAANN9266** [comment]
Here is another account on a different pub. This one only has 1 invite.  

Logged into member account (Gene Vincent, #34668, lstarkweconversion+JPC@gmail.com/password1)
Selected Share Your Subscription from drop down menu
Invited Test TestingJCP3a 
Received email and clicked on link "Accept Your Invitation"
Redirected to webpage with error message (see attachment below)
![shareerror4](https://cloud.githubusercontent.com/assets/25617462/23070543/413ff92c-f4e0-11e6-83a9-6bb05f539867.PNG)

**Comment by mkoza178** [comment]
Ah okay. I see, it's taking you to AJC's Test site. Check the url. 

I updated the url in the email. I thought I did this before...gonna double check all the props again though. Try now.

**Comment by LISAANN9266** [comment]
Yes, it worked for the TestingJCP3a.  I will see about resending an invite in the other market and see if it works.

**Comment by LISAANN9266** [comment]
All good!
