### ISSUE TITLE
Nola - error for vacation on mail sub - duplicated text

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#18]
In the error returned for a mail sub attempting to enter a vacation stop, the text is duplicated:

![image](https://cloud.githubusercontent.com/assets/25667903/23069579/9e836ff8-f4ed-11e6-934b-8310696951bd.png)

**Comment by mkoza178** [comment]
This error is in CMS. I removed the extra text. Check now!

**Comment by beckywallace** [comment]
Looks good, thanks!
