### ISSUE TITLE
GRP_Share_Subscription_showing as pending and current member?

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#19]
I shared my subscription, received the email, logged in using the link in the email. Looking at the share my subscription screen, it's showing the email address i shared under pending invites and under current members.
![grp_sharesubscription_showing as current member and pending](https://cloud.githubusercontent.com/assets/25616655/23080558/30a35de0-f51f-11e6-84ca-49c03ff3dbad.png)

**Comment by mkoza178** [comment]
Hey Amanda, 

I'm unable to reproduce this. Can you give me steps on how to reproduce this?

**Comment by apattok** [comment]
Even after I've accepted the invite and created an account, i'm still seeing it in both spots:

![bct_sharesubscription_showing as current member and pending](https://cloud.githubusercontent.com/assets/25616655/23326768/c8475d30-facf-11e6-8924-11a631a4bae5.png)

**Comment by apattok** [comment]
It's definitely when you re-send the invite. Something goes screwy. Email sends, but then you can't accept invite and it puts the email address in both pending and current member.

**Comment by mkoza178** [comment]
Amanda, can you still reproduce this? We cannot.
