### ISSUE TITLE
Update Payment Screen

### ISSUE THREAD

**Issue by LISAANN9266** [mkoza178/Advance---MI-Merge#21]
EZ Pay needs to be changed to Easy Pay.  This is for all pubs.

![updatepymt2](https://cloud.githubusercontent.com/assets/25617462/23188314/1a966dcc-f843-11e6-9c65-c1efcfdb6a77.PNG)

Only One Payment - after customercare@mlive.com there needs to be a space added.
![updatepymt1](https://cloud.githubusercontent.com/assets/25617462/23188188/b4d05818-f842-11e6-9245-ad56b4cc8a54.PNG)

**Comment by mkoza178** [comment]
Looks like someone updated to Easy Pay for all T & C for all pubs. 
Updated the error message in notifications in CMS 

Take a look now.

**Comment by LISAANN9266** [comment]
So, when we go live, the verbiage for T & C's will be correct and the error message will be too?

**Comment by mkoza178** [comment]
We will be copying the data from Test to Prod. So, yes.

**Comment by LISAANN9266** [comment]
Then what I saw in Test (Ann Arbor) - nothing had changed.  I cleared cache and still have the same problems.

**Comment by LISAANN9266** [comment]
Still showing EZ Pay, instead of Easy Pay.

![updatepymt4](https://cloud.githubusercontent.com/assets/25617462/23861729/2fef1162-07c8-11e7-8e79-26937ed8202c.PNG)

Only One Payment in 24 hours - This verbiage has been fixed.

**Comment by mkoza178** [comment]
Updated in CMS. 

Clear your cache and check in 5 minutes!

**Comment by LISAANN9266** [comment]
Looks good.
