### ISSUE TITLE
Payment Update - Ann Arbor 

### ISSUE THREAD

**Issue by LISAANN9266** [mkoza178/Advance---MI-Merge#22]
I've tried two different accounts in Ann Arbor and both times I get an error message. I am unable to update payment. 

lstarkweconversion+aan20@gmail.com
lstarkweconversion_aan20b@gmail.com

![updatepymt3](https://cloud.githubusercontent.com/assets/25617462/23222221/124fb828-f8dc-11e6-8b07-099502a9be88.PNG)

**Comment by mkoza178** [comment]
Try now, we had an incorrect Edgil url

**Comment by LISAANN9266** [comment]
Works now.  Thanks for the fix.
