### ISSUE TITLE
Not getting to dssConfirm when activating account

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#23]
When activating a subscriber account and clicking Submit on dssSubscribe, screen flashes and keeps user on dssSubscribe page.  When clicking submit again, user is presented with the following error:
![image](https://cloud.githubusercontent.com/assets/25667903/23318778/6c39fef2-fa99-11e6-96c2-3898690f7d76.png)

Clicking Submit should immediately take subscriber to the dssConfirm page:
![image](https://cloud.githubusercontent.com/assets/25667903/23318790/8429c5b0-fa99-11e6-808f-c935ed6d3e03.png)

**Comment by mkoza178** [comment]
TFS 34547

**Comment by beckywallace** [comment]
@mkoza178  - not sure what Share My Subscription has to do with this issue?

**Comment by mkoza178** [comment]
Share Your Subscription uses the dssMatch flow.

**Comment by beckywallace** [comment]
@mkoza178 - just re-tested this and still receiving the same results

**Comment by beckywallace** [comment]
This appears to be corrected.
