### ISSUE TITLE
Share My Subscription_Welcome Confirmation Email 

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#24]
After you accept the invite and create a password, an email automatically sends to the shared email addresses congratulating them on their my Michigan membership, but it's in the name of the actual account holder and not the name of the person they've shared it with. Any way to change that? Name should be Bay City Test2, not WILMA.

![share_my_subscription_welcome_email](https://cloud.githubusercontent.com/assets/25616655/23326961/7d9027b0-fad2-11e6-92d7-4a92b2537e30.png)

**Comment by mkoza178** [comment]
Unfortunately, no because these event type id's are 63's which pulls the first_name from the event log. 
It'd require great effort to change. 

My suggestion would be to either strip out the 'Dear first_name' part or send the user's email address they signed up with.

**Comment by mkoza178** [comment]
Change 'dear first_name' text to be more generic. Will circle back on this.
