### ISSUE TITLE
TFS 34555 Share my Subscription_Pending Invites Shifted when re-sending invite

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#25]
when you have multiple pending invites and you re-send one of them, all of the pending invites shift and are visually odd. If you refresh your screen, it goes back to normal. Not high priority, just odd.

![share my subscription_re_send invite - pending invites look funny](https://cloud.githubusercontent.com/assets/25616655/23327158/2c1ec438-fad5-11e6-9000-05133e3d3b3b.png)

**Comment by mkoza178** [comment]
Reproduced.

TFS 34555 created

**Comment by mkoza178** [comment]
Re-test, looks good to me.

**Comment by apattok** [comment]
tested - resolved.
