### ISSUE TITLE
Share My Subscription - When accepting invite & adding password, you have to click save twice

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#26]
When you click to accept the invitation in your email, it brings you to create a password, After you do that,  you click submit and it does nothing. No "success or congratulations message" so you think it didn't work. If you click submit a second time, it tells you that you've already registered. Very confusing. Also, shouldn't there be a link to the members home page. Doesn't really tell the invited person where to go. Would be helpful.

![share my subscription_accept_invite_have to click submit twice](https://cloud.githubusercontent.com/assets/25616655/23327178/9125e096-fad5-11e6-8fde-04b16f1f440c.png)

**Comment by mkoza178** [comment]
Closing as we are tracking this bug in github #23
