### ISSUE TITLE
TFS 34556 Share My Subscription - No Save Button on Mobile Phone

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#27]
Opened invitation email and clicked accept. asked for my password and to check the box to accept the T&Cs but there's not SUBMIT button, so you can't complete the process on a mobile phone, android or iphone. Or tablet.

**Comment by mkoza178** [comment]
Reproduced. TFS 34556 created

**Comment by mkoza178** [comment]
This is resolved. Please re-test.

**Comment by apattok** [comment]
tested - resolved.
