### ISSUE TITLE
FJNL - Update Payment - add space in error message

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#28]
need space after email address and before the word and.
![fjnl - update payment - error message needs spacing in wording](https://cloud.githubusercontent.com/assets/25616655/23327899/c71293f4-fae2-11e6-8835-16e7e9bbc130.png)

**Comment by mkoza178** [comment]
Try now. Updated the message in notifications in CMS.

**Comment by apattok** [comment]
Resolved. Thanks!
