### ISSUE TITLE
TFS 34306, 34307, 34308, Update Email - Search Result in Admin showing Invalid parameter value

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#3]
Updated email looked successful on the members site. Kalamazoo customer 51175354, updated email from Amanda.Pattok@gmail.com to Amanda.Pattok+GAZ@gmail.com. Looking in the admin, i'm not seeing anything other than Invalid Parameter Value, and doesn't list customer info.
![invalid parameter value_update email](https://cloud.githubusercontent.com/assets/25616655/22836413/45b2b59a-ef8a-11e6-9c4b-4f4702a47d06.png)

**Comment by mkoza178** [comment]
TFS 34306 - Save more data on event 21's. 
TFS 34307 - sitecode is MI. Should be sitecode of user. 
TFS 34308 - invalid publication error in Admin event viewer

**Comment by mkoza178** [comment]
34306 - ready to re-test
34307 - ready to re-test
34308 - ready to re-test

**Comment by apattok** [comment]
tested and resolved.
