### ISSUE TITLE
Nola - Update payment text missing

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#30]
The text that we currently see in production when updating payment information is not showing in test.  Additionally, T's and C's are missing

**Production**
![image](https://cloud.githubusercontent.com/assets/25667903/23411382/c4b99f1e-fd97-11e6-9dc2-ecf83047e05b.png)

**Test**
![image](https://cloud.githubusercontent.com/assets/25667903/23411418/daf5df90-fd97-11e6-9862-332babf915fc.png)

**Comment by mkoza178** [comment]
Updated in CMS. Copied Prod copy to Test.
