### ISSUE TITLE
Nola - PN references in account activation confirmation email

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#31]
![image](https://cloud.githubusercontent.com/assets/25667903/23411831/3263339e-fd99-11e6-9fdd-d3f74bebc25b.png)

**Comment by mkoza178** [comment]
Updated in the Admin event type emails.
Copied data from Prod to Test.

**Comment by beckywallace** [comment]
Verified:

![image](https://cloud.githubusercontent.com/assets/25667903/23570716/26d91c2a-002b-11e7-9e17-553e9c54cbc9.png)
