### ISSUE TITLE
Nola - need Easy Pay text on dssSubscribe page

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#34]
![image](https://cloud.githubusercontent.com/assets/25667903/23414749/a38bbe48-fda2-11e6-8de0-1d88f0697ed2.png)

**Comment by mkoza178** [comment]
This is a bug. 

This is a setting in CMS that isn't displaying correctly. 

TFS 34644

**Comment by mkoza178** [comment]
Fixed. Test now. This page is now respecting CMS setup.

**Comment by beckywallace** [comment]
Looks good:

![image](https://cloud.githubusercontent.com/assets/25667903/23672642/eb012b2c-0334-11e7-9e4c-c2102f456545.png)
