### ISSUE TITLE
FJNL - Confirmation on MissedPaper.aspx

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#35]
After submitting the complaint and the page is refreshed - the confirmation information is at the bottom of the page but the fact that the first thing you see is "We're sorry you're experiencing an issue....".  Thoughts on having the confirmation message moved up on the page? 

![image](https://cloud.githubusercontent.com/assets/25667903/23509730/67ea577a-ff1c-11e6-9512-d950702f6b9b.png)

**Comment by mkoza178** [comment]
Move notification message to top.

**Comment by mkoza178** [comment]
TFS 34695

**Comment by mkoza178** [comment]
Please re-test. The message is now moved to the top.

**Comment by beckywallace** [comment]
Beautiful!  Thank you!
![image](https://cloud.githubusercontent.com/assets/25667903/23717688/6ada862a-03fa-11e7-8705-1064806b5839.png)
