### ISSUE TITLE
Nola - redelivery option not available

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#36]
Submitting a complaint for yesterday's pub date - redelivery option is not shown, only option is to credit account:

![image](https://cloud.githubusercontent.com/assets/25667903/23510794/8bcab366-ff20-11e6-8c40-1e5c09566ad7.png)

**Comment by mkoza178** [comment]
According to the flowcharts, the only option to show 
![priorday](https://cloud.githubusercontent.com/assets/23486770/23518511/a7479d90-ff41-11e6-949d-791ada5dcaed.jpg)
for a prior day is Credit. Attaching image of flowchart.
