### ISSUE TITLE
FJNL Redelivery - error text in Event Processing Result does not match error returned

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#37]
**Error in Event Processing Result:**

![image](https://cloud.githubusercontent.com/assets/25667903/23510945/1d92213a-ff21-11e6-9aa1-6c7503eedeaa.png)

**Error in Actual Response**
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Service Error Transaction</title>
</head>
<body>
<form name="serverrtran" method="post" action="serverrtran.html">
<h3>Service Error Transaction</h3>
<table>
  <tr>
    <td>Return Status:&#160;<ReturnStatus>Error</ReturnStatus></td>
  </tr>
  <tr>
        <td>Error Code:&#160;<ErrorCode>423</ErrorCode></td>
  </tr>
  <tr>
        <td>Error Msg:&#160;<ErrorMsg>**Incident date cannot be after 11/24/16**.  (423)</ErrorMsg></td>
  </tr>
</table>
<p><a href="login.html?stateInfo=dNcibpdcdh|3">Back to Login Menu</a></p>
</form>
</body>
</html>

**Comment by mkoza178** [comment]
This cannot be updated. I'll explain why on our daily stand up tomorrow. 

It has more to do with DTI's pub date changing.
