### ISSUE TITLE
FJNL - Delivery complaint appears processed but error in SubCon

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#38]
When submitting a delivery complaint (I used Missed Paper - both to credit account, and to redeliver - during redelivery times), the customer gets a confirmation message however in SubCon an error was returned and no transaction gets to DTI.  See Event ID 530714

![image](https://cloud.githubusercontent.com/assets/25667903/23528605/0a29c4ba-ff60-11e6-87b8-d1017628fe0d.png)

![image](https://cloud.githubusercontent.com/assets/25667903/23528512/bda087d2-ff5f-11e6-92c7-acad96fc6fe9.png)

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Service Error Transaction</title>
</head>
<body>
<form name="serverrtran" method="post" action="serverrtran.html">
<h3>Service Error Transaction</h3>
<table>
  <tr>
    <td>Return Status:&#160;<ReturnStatus>Error</ReturnStatus></td>
  </tr>
  <tr>
        <td>Error Code:&#160;<ErrorCode>423</ErrorCode></td>
  </tr>
  <tr>
        <td>Error Msg:&#160;<ErrorMsg>Incident date cannot be after 11/24/16.  (423)</ErrorMsg></td>
  </tr>
</table>
<p><a href="login.html?stateInfo=lYapbndGwl|3">Back to Login Menu</a></p>
</form>
</body>
</html>

**Comment by mkoza178** [comment]
Updated. Take a look.
