### ISSUE TITLE
Redelivery Testing - 

### ISSUE THREAD

**Issue by JLewis12** [mkoza178/Advance---MI-Merge#39]
BCT did not show a delivery option at 1:53 PT (4:53 ET) on showed eEdition.   Time show delivery until 7pm. 

Hello, JACKIE ADAMO. You are currently managing the subscription for The Bay City Times Account # 50565852.

![bct no redelivery option](https://cloud.githubusercontent.com/assets/26151269/23528824/08823896-ff50-11e6-830b-c012b70956d8.JPG)

**Comment by mkoza178** [comment]
So, according to the rules we have in the publications table. On Thursday the open is 6:30am EST and close is 3pm EST. Is this correct?

Or is what is appearing on the page, correct?

**Comment by apattok** [comment]
Marc, here is what is currently set up for Bay City....timings must have changed at some point.....
![bct_redelivery schedule](https://cloud.githubusercontent.com/assets/25616655/23562019/b718e800-000e-11e7-8e04-e11e686af92c.png)

**Comment by mkoza178** [comment]
Times have been updated since yesterday based off what Amanda has sent me.
