### ISSUE TITLE
Create Account Page showing Grand Rapids Press for all pubs

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#4]
When creating an account, after entering in last name and account number, it asks for you to create a password, but the heading says Grand Rapids PressUser Information, no matter which pub you are registering.
![create account_defaults grand rapids press](https://cloud.githubusercontent.com/assets/25616655/22837182/747c3a60-ef8d-11e6-91a4-5baf353ffb32.png)

**Comment by mkoza178** [comment]
TFS 34310

**Comment by mkoza178** [comment]
Please re-test, looks good.

**Comment by apattok** [comment]
Resolved.
