### ISSUE TITLE
Nola - wrong code for Missed Paper - credit

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#40]
Submitting a delivery complaint for a missed paper, selecting credit option - complaint code being sent is PRIORCR which is not valid for Nola.  In production we receive G2MISSCR.  Reference event ID 532754.

**Comment by mkoza178** [comment]
The complaint code we sent was 'Credit'. 

According to the flowcharts this is correct. 
![credit](https://cloud.githubusercontent.com/assets/23486770/23558671/702caad2-0002-11e7-94c3-64f58705486a.jpg)

Updated rejection text to match the new complaint code. Looks like this complaint code is not setup in NOLA test DTI possibly.

**Comment by beckywallace** [comment]
1 - Credit is also not a valid code for Nola
2 - The error message indicates the code was PRIORCR - another scneario where this error does not match the actual error returned:
![image](https://cloud.githubusercontent.com/assets/25667903/23558815/8f4e0cec-fffa-11e6-9a2d-268a7738306d.png)
![image](https://cloud.githubusercontent.com/assets/25667903/23558861/c5a690fc-fffa-11e6-88da-04939a2dbbb2.png)

**Comment by mkoza178** [comment]
1. It needs to be according to the standard flow charts.
2. I updated the message.

**Comment by beckywallace** [comment]
OK, I'm following up.  Had not yet been informed of any  new codes for Nola.

**Comment by mkoza178** [comment]
No problem. Check the redelivery tab on the flowcharts I sent to you. It has all the applicable codes.

**Comment by beckywallace** [comment]
Codes need to be added for Nola.
