### ISSUE TITLE
Nola - sub currently on vacation able to submit additional vacation request

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#41]
Subscriber is currently on vacation, receives message that records indicate vacation but they are still able to submit vacation – expected results on spreadsheet indicate there should be no access for subs already on vacation?  If they are supposed to be able to submit an additional vacation request, probably need to change up the text on the message?
 
![image](https://cloud.githubusercontent.com/assets/25667903/23557912/5d7d8934-fff7-11e6-8060-63e2462a2df9.png)

 
![image](https://cloud.githubusercontent.com/assets/25667903/23557923/61fad570-fff7-11e6-8f77-5e5c54f106b4.png)

![image](https://cloud.githubusercontent.com/assets/25667903/23557929/672548f0-fff7-11e6-9709-d24f1f9fbe33.png)

**Comment by mkoza178** [comment]
TFS 34632

**Comment by mkoza178** [comment]
Resolved, give a test!

**Comment by beckywallace** [comment]
Fixed!  Thank you.
