### ISSUE TITLE
GRP_Make A Payment_No on screen confirmation

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#42]
Submitted my payment, just goes to blank screen...
![grp_make_payment](https://cloud.githubusercontent.com/assets/25616655/23563116/3d57db3e-0013-11e7-9242-2fbe76e8c908.png)

**Comment by mkoza178** [comment]
Yup, we saw this too. 

TFS 34583

**Comment by mkoza178** [comment]
This is working now. If it fails, we receive the correct error message.

**Comment by apattok** [comment]
I did receive an error message that my payment could not be processed at this time and to call customer service.
