### ISSUE TITLE
GRP_EasyPay_made payment today but can still sign up for easy pay

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#43]
Won't let me do another one time payment but is letting me sign up for easy pay
![grp_madepaymenttoday_cansignupforeasypay](https://cloud.githubusercontent.com/assets/25616655/23564270/d729e2e4-0017-11e7-9e98-53178f40b2ed.png)

**Comment by mkoza178** [comment]
I believe this is because the event failed, so we didn't stop them from trying to sign up for Easy Pay. I'd need to think about this...

**Comment by mkoza178** [comment]
Tested this just now. I made a payment, successfully and was blocked from doing an Ezpay.
I believe the rule is: IF event is Not successful, allow them to try an EZpay.
