### ISSUE TITLE
TFS 34655 GRP_Both Payment Attempts Failed

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#44]
No error message on members page. Both payments failed: 
![grp_makepayment_paymentfailed2](https://cloud.githubusercontent.com/assets/25616655/23564798/75766a8e-0019-11e7-9e64-294b17539319.png)
![grp_makepayment_paymentfailed](https://cloud.githubusercontent.com/assets/25616655/23564799/7578c00e-0019-11e7-9f9a-9958f71c65c2.png)

**Comment by apattok** [comment]
Tried CC with no tip, same error: 
![grp_makepayment_paymentfailed3](https://cloud.githubusercontent.com/assets/25616655/23565043/1324de46-001a-11e7-9338-4641adc1b3e3.png)

**Comment by mkoza178** [comment]
TFS 34655

**Comment by mkoza178** [comment]
We resolved this error but now getting: Production server host name Business Rule is invalid.  (259)

From DTI. This needs to be resolved by Advance/DTI.

**Comment by mkoza178** [comment]
Still recieving this DTI error: 

Production server host name Business Rule is invalid.  (259)

**Comment by apattok** [comment]
Payments going into DTI test okay.
