### ISSUE TITLE
TFS 34654 GRP_MakePayment _Checking Payment Failed

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#46]
What's this error mean? I used my actual checking info...
![grp_makepayment_checking failed](https://cloud.githubusercontent.com/assets/25616655/23565446/a2594f56-001b-11e7-9646-c365b99ea5b3.png)

**Comment by mkoza178** [comment]
TFS 34654

**Comment by mkoza178** [comment]
Test now. No longer receiving this error.

**Comment by apattok** [comment]
Looks good on members site and in admin. Would like to confirm email sent to customer care to start service and BD payment is in the payment file for this account: 
![bdpayment_restart](https://cloud.githubusercontent.com/assets/25616655/24461193/6500f3a4-146e-11e7-8d87-364354461b02.png)

**Comment by mkoza178** [comment]
Give this a test Amanda. The payment amount should be coming through now on the email.
