### ISSUE TITLE
GRP_RegistrationFailed

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#48]
Error messages needs to be configured, assuming CMS.
![grp_failed registration](https://cloud.githubusercontent.com/assets/25616655/23566404/b9462212-001f-11e7-93bb-4f42c7cbff3a.png)

**Comment by mkoza178** [comment]
Hm I tested with the same data and had no issue. 

I see no telephone is set. That's odd. I wonder if no sitecode is set. Can you tell me how to reproduce?

**Comment by apattok** [comment]
not sure. it was my actual account and it works fine now....???

**Comment by mkoza178** [comment]
Got me. I haven't seen this before.

**Comment by mkoza178** [comment]
Okay to close this?
