### ISSUE TITLE
Can't Register JCP Subscriber

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#5]
Not able to register JCP subscribers...
![jcp_can t register account](https://cloud.githubusercontent.com/assets/25616655/22840485/ba1cb208-ef9b-11e6-8349-8d77054edce8.png)

**Comment by mkoza178** [comment]
TFS 34309

**Comment by mkoza178** [comment]
Re-test, should be good.

**Comment by apattok** [comment]
Resolved.
