### ISSUE TITLE
Update Copy to indicate eEdition access

### ISSUE THREAD

**Issue by JLewis12** [mkoza178/Advance---MI-Merge#50]
After entering a service issue - this message it presented - when you click the "Click Here" it take you to the e-Edition.. The message should indicate you are being given e-Edition access. 

"Your transaction has been processed. Please **Click Here** to access to the Grand Rapids Press **e-Edition**.

![image](https://cloud.githubusercontent.com/assets/26151269/23620676/a4e5e0bc-024c-11e7-9ec3-ad9711d7b9c5.png)

**Comment by mkoza178** [comment]
Hey Jason, 

This is update able under CMS, notifications. 
![notifications](https://cloud.githubusercontent.com/assets/23486770/23623744/227c0c44-0271-11e7-8887-598d98813308.jpg)

Would you like me to update or do you want to? Trying to get you acclimated to the notifications section.
