### ISSUE TITLE
TFS 34698 Redelivery - only have option for e-Edition

### ISSUE THREAD

**Issue by JLewis12** [mkoza178/Advance---MI-Merge#51]

**Comment by JLewis12** [comment]
Setup is for re-delivery between 8am-12.  Time is 9:06 account 50565852..   

When I tried another account 100218  - I got both options but then the system reported back error (There was a problem at the moment of processing your complaint. Please contact Customer Service at (989) 671-1201 for additional assistance)

![image](https://cloud.githubusercontent.com/assets/26151269/23659981/d2010418-02fc-11e7-84f1-f6605667110a.png)

![image](https://cloud.githubusercontent.com/assets/26151269/23660013/e9dd9fc4-02fc-11e7-9610-1c7d08980dc9.png)

**Comment by mkoza178** [comment]
TFS 34698

**Comment by mkoza178** [comment]
Resolved, please re-test when in window!

**Comment by apattok** [comment]
tested - resolved.
