### ISSUE TITLE
FJNL - Publication name missing from Welcome message on dssSubscribe

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#52]
![image](https://cloud.githubusercontent.com/assets/25667903/23661307/f2633ebe-0311-11e7-8c1a-f3c72cbef5ea.png)

**Comment by mkoza178** [comment]
TFS 34701

**Comment by mkoza178** [comment]
This is resolved. Please confirm!

**Comment by beckywallace** [comment]
Looks good:

![image](https://cloud.githubusercontent.com/assets/25667903/23860602/6d367788-07d5-11e7-8659-f482eb6e8544.png)
