### ISSUE TITLE
NOLA - Text references Post-Standard on Payment.aspx page

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#53]
![image](https://cloud.githubusercontent.com/assets/25667903/23666116/ebb89696-031f-11e7-8fa1-7972cd60bdc4.png)

**Comment by mkoza178** [comment]
Updated in CMS -> Content - Payment page.

Check now.

**Comment by beckywallace** [comment]
Looks good:

![image](https://cloud.githubusercontent.com/assets/25667903/23672532/a736a8a4-0334-11e7-9a6f-fe919ee4b013.png)
