### ISSUE TITLE
Nola - Missing TV Week option in Delivery Issues

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#54]
Missing TV Week should not be an option for Nola:

![image](https://cloud.githubusercontent.com/assets/25667903/23707896/a01556f6-03d9-11e7-8f8e-01a071610380.png)

**Comment by mkoza178** [comment]
TFS 34715

**Comment by mkoza178** [comment]
This is resolved. Please test and confirm.

**Comment by beckywallace** [comment]
looks good, thanks!
![image](https://cloud.githubusercontent.com/assets/25667903/23717656/4765e73e-03fa-11e7-8777-4227f434080e.png)
