### ISSUE TITLE
NOLA - Unable to submit complaint for different delivery day after 2 complaints submitted for separate days

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#55]
I was able to submit a complaint for 3/5 (credit) and for 3/8 (redelivery) for the subscriber (reference event IDs 536753 and 536754).  When attempting to submit an additional complaint for a different date, the following message is displayed and nothing is logged in SubCon:

![image](https://cloud.githubusercontent.com/assets/25667903/23709391/e0db3714-03de-11e7-822f-b6cae4af9536.png)

**Comment by mkoza178** [comment]
Can you try incognito or private browsing just to be sure?

I logged into NOLA with account 17648 and submitted these event ids, each for different dates:

536781
536780
536779
536778
536777

**Comment by beckywallace** [comment]
![image](https://cloud.githubusercontent.com/assets/25667903/23710798/8e79229c-03e3-11e7-8d64-1ce90e349401.png)

**Comment by beckywallace** [comment]
@mkoza178 - I don't know how to assign this back to you?

**Comment by beckywallace** [comment]
oh wait sorry - wrong issue :)

**Comment by beckywallace** [comment]
It allowed the transaction now - but not sure why it didn't initially???  I'm going to do the same with another subscriber.

**Comment by beckywallace** [comment]
Tried with another account and was successful - maybe some odd glitch going on at the time I tried the other??
