### ISSUE TITLE
NOLA - Redelivery email has PN graphic, text

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#56]
![image](https://cloud.githubusercontent.com/assets/25667903/23709868/6c441ab8-03e0-11e7-8b5a-e3364eea0b7b.png)

**Comment by mkoza178** [comment]
Updated. Take a look now.

**Comment by beckywallace** [comment]
Not giving me the redelivery option now when I select today's date?  We are still within the redelivery window.

**Comment by mkoza178** [comment]
I just logged in with an account and saw redelivery today. What is the account # you are using?

**Comment by beckywallace** [comment]
Account 353875

**Comment by beckywallace** [comment]
![image](https://cloud.githubusercontent.com/assets/25667903/23710384/29d20922-03e2-11e7-92f1-02813f164e23.png)

**Comment by mkoza178** [comment]
For that account the redelivery flag = NO, thus we do not allow redelivery for them. Account 353875

**Comment by beckywallace** [comment]
![image](https://cloud.githubusercontent.com/assets/25667903/23711316/1f16434c-03e5-11e7-87c7-c8cb044dec74.png)
