### ISSUE TITLE
Can't register MC Subscriber

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#6]
Can't register Muskegon account.
![mc_can t register account](https://cloud.githubusercontent.com/assets/25616655/22841567/1b498976-efa0-11e6-9d99-68eaf9a62f29.png)

**Comment by mkoza178** [comment]
TFS 34309

**Comment by mkoza178** [comment]
Go ahead and re-test!

**Comment by apattok** [comment]
Resolved.
