### ISSUE TITLE
TFS 34734 NOLA - if Get Payment call fails (34) do not display the payment page

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#60]
Sub is stopped with no previous balance (i.e. no amount owed):

![image](https://cloud.githubusercontent.com/assets/25667903/23764323/c0487590-04c2-11e7-9e1d-b47c5fc0694e.png)

**Comment by mkoza178** [comment]
This sub, in G2 data, is Active.

**Comment by beckywallace** [comment]
ugh, then that's another issue - why no payment terms presented?  @mkoza178 (I still don't know how to assign to you)

**Comment by mkoza178** [comment]
This error: 

No active subscriptions found.  (113)

from DTI. None were returned.

**Comment by beckywallace** [comment]
ok, so then they shouldn't be presented with the payment page in that case, right?

**Comment by mkoza178** [comment]
Agreed. TFS 34734

**Comment by mkoza178** [comment]
Becky, this looks good. Please re-test. You can use same account. 

CMS notifications for the error messages on ezpay and payment are as follows:
ezpayUnableToShowEZPayOptions and paymentCantAccessPaymentOptions
