### ISSUE TITLE
NOLA - Account is past due text on payment for stopped sub

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#61]
The text advising the account is past due is in between the restart vs not starting the account.  Can this be moved above the balance display, and maybe bolded?

![image](https://cloud.githubusercontent.com/assets/25667903/23764726/315ba800-04c4-11e7-9998-0786c914189e.png)

**Comment by mkoza178** [comment]
TFS 34733 created

**Comment by mkoza178** [comment]
This is done. Please review.

**Comment by beckywallace** [comment]
Looks good:

![image](https://cloud.githubusercontent.com/assets/25667903/23860679/a769a27c-07d5-11e7-9054-14fb97c5ddc8.png)
