### ISSUE TITLE
NOLA - Easy Pay signup bill change has reason of "GIFT10"

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#62]
Signed subscriber 103594 up for Easy Pay

![image](https://cloud.githubusercontent.com/assets/25667903/23766832/fc3c6f44-04cb-11e7-9ebe-69ec7bec1fdf.png)

![image](https://cloud.githubusercontent.com/assets/25667903/23766846/0a44fb56-04cc-11e7-9497-64b8943991a2.png)

**Comment by mkoza178** [comment]
Unsure on this one. We do not pass a reason code. 
Is there a configuration in DTI causing this?

**Comment by beckywallace** [comment]
Business rule "What is the reason code for auto renew billing change transactions?"
