### ISSUE TITLE
TFS 34996 NOLA - Easy  pay signup confirmation page

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#63]
The confirmation page doesn't include mention of the grace amount that will also be collected (in this case $3.88)

![image](https://cloud.githubusercontent.com/assets/25667903/23769117/ea340e62-04d3-11e7-957e-0fc27a89a15a.png)

**Comment by mkoza178** [comment]
I think we want to have a discussion on this first before we move forward.

**Comment by mkoza178** [comment]
Add Current Grace Past Due line item. 
Change  EasyPay line item to:  EasyPay Term Amount


Remove Total Amount line item? Marc to review.

**Comment by apattok** [comment]
ready for internal MG2 testing, we can test also.

**Comment by beckywallace** [comment]
There is still no Current Grace Past Due item, and total does not reflect the grace amount:

![image](https://cloud.githubusercontent.com/assets/25667903/24417935/f823ace0-13af-11e7-8ceb-61d2cd725ded.png)

**Comment by mkoza178** [comment]
We agreed to standardize the page to only show the amount the customer is paying to simplify. TFS 34996.

**Comment by mkoza178** [comment]
The confirmation page is now standardized. Please review in Test.

**Comment by beckywallace** [comment]
Total amount on confirmation page is only showing term amount, not including grace amount:

This is for subscriber 129129 (occupant 1080793):
![image](https://cloud.githubusercontent.com/assets/25667903/24631033/8955d2aa-1884-11e7-864f-4490ff16beb8.png)
![image](https://cloud.githubusercontent.com/assets/25667903/24631036/8d2c02aa-1884-11e7-8678-47a64b3681e9.png)

**Comment by mkoza178** [comment]
Yes because we technically never include the grace amount in what we send to DTI for ezpay flow.


-------- Original message --------

**Comment by beckywallace** [comment]
We've been back and forth on this one so much I forget what we finally agreed to.  Maybe this is the one where we said we're going to have to be very specific in the wording for what the customer is agreeing to with their past due amount.  Let me see what the file looks like tomorrow - should have one payment for the total amount vs. 1 for Easy Pay term and 1 for grace payment.

**Comment by mkoza178** [comment]
No file for easy pay flow.


-------- Original message --------

**Comment by beckywallace** [comment]
This was a subscriber in grace - where am I going to see their grace payment??

**Comment by mkoza178** [comment]
Right now the easy pay flow for a subscriber in grace is purely informational. We do not do a grace pay for them.


-------- Original message --------

**Comment by beckywallace** [comment]
Yep (banging my  head against the wall) - this is the one where we have to manage expectations with the wording.  It's been a long day!

**Comment by mkoza178** [comment]
No problem!


-------- Original message --------
