### ISSUE TITLE
NOLA - Invalid account type being sent for bank draft payments

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#64]
CK is being sent instead of Checking, SA is being sent instead of Savings - DTI is returning error for invalid account type:

 
![image](https://cloud.githubusercontent.com/assets/25667903/23772470/ab6b5e80-04e0-11e7-842c-7396419ebe54.png)

![image](https://cloud.githubusercontent.com/assets/25667903/23772474/b0c519d4-04e0-11e7-8b24-bdf1276558ca.png)

 
![image](https://cloud.githubusercontent.com/assets/25667903/23772477/b4b3033a-04e0-11e7-951c-af6dbf6ab285.png)

![image](https://cloud.githubusercontent.com/assets/25667903/23772481/b885e130-04e0-11e7-9eae-96bae6930d13.png)

![image](https://cloud.githubusercontent.com/assets/25667903/23772490/bd3f4770-04e0-11e7-81b7-1160f29a4e8c.png)

![image](https://cloud.githubusercontent.com/assets/25667903/23772500/c1a44be4-04e0-11e7-9e50-d35f267e7756.png)

 
![image](https://cloud.githubusercontent.com/assets/25667903/23772504/c4d980ea-04e0-11e7-93b0-8f8e82593d33.png)

 
![image](https://cloud.githubusercontent.com/assets/25667903/23772507/c7f0372e-04e0-11e7-972a-6133e23e93f7.png)

**Comment by mkoza178** [comment]
TFS 34753

**Comment by mkoza178** [comment]
Resolved. Give a go!

**Comment by beckywallace** [comment]
Correct value now sent for both checking and savings.
