### ISSUE TITLE
TFS 34598 NOLA - No info in eBill file for previous day eBill signup

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#65]
I signed up subscriber 77243 for ebilling yesterday (3/9) (events listed below).  The ebill file received did not include any data (unable to attach the file as it is an empty file).

![image](https://cloud.githubusercontent.com/assets/25667903/23797440/808cedde-0565-11e7-87ef-e926cead39af.png)

**Comment by mkoza178** [comment]
Yep. Not sure why that is. TFS 34598

**Comment by mkoza178** [comment]
3/10 file had data. Going to make sure future dates have data before closing.

**Comment by mkoza178** [comment]
File is generating data but some data looks wrong on a file generated 3/17. Fired a new event today to check tomorrow's file.

**Comment by mkoza178** [comment]
File looks good today. Sent to Jon and Amanda for their verification.

**Comment by mkoza178** [comment]
JVZ confirmed eBill file loaded without issue.
