### ISSUE TITLE
TFS 34754 NOLA - No RSTPay file received, restart payment not in other files

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#66]
Below are the files that were available today:

![image](https://cloud.githubusercontent.com/assets/25667903/23797601/49409424-0566-11e7-97aa-1753248f4286.png)

Since the TPDNRPayments file is still there, I would expect (?) to also see the TPRSTPay file which is not in the available files.

See the below events for a payment that was made to restart a stopped subscriber.  I checked the TPDNRPayments and TPGracePayments as well to see if it got in the wrong file but this subscriber is not in either of those files.

![image](https://cloud.githubusercontent.com/assets/25667903/23797585/377e2080-0566-11e7-80bc-eb8fe4028600.png)

**Comment by mkoza178** [comment]
The file name is called "SolicitorConPayments" in Test because we never updated it to be the same as the prod one. But that is blank. TFS 34754

**Comment by mkoza178** [comment]
These files are being generated with data. Closing this guy out.
