### ISSUE TITLE
NOLA - Billed start failing due to Edgil transaction. 

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#67]
The TPFailedStartBK file includes records for starts that were successful. These both appear to be the billed starts via SolCon yet a payment is included in the file???  The starts would error since it is already active and the payments would error since we don't have a payment type but these should not have been in the file at all.  SubCon shows an "Edgil Capture failed" for Pam Smallpage.  There should not have been an Edgil call for a billed order.  I'm unable to find the "Becky BilledTest" in SubCon?

![image](https://cloud.githubusercontent.com/assets/25667903/23797865/86f2ace8-0567-11e7-85ab-a37246eca9e3.png)

![image](https://cloud.githubusercontent.com/assets/25667903/23797955/ef7c4ada-0567-11e7-8c6e-4f560cd492fc.png)

**Comment by mkoza178** [comment]
No point in looking at these as they go the way of the dinosaur at time of go live.

**Comment by beckywallace** [comment]
So do those records end up in another file?  I'm concerned that the system thinks there was a payment associated with the start, and that it thinks the start failed.

**Comment by mkoza178** [comment]
No file. Failed starts need to be re-processed via the admin event viewer process.

**Comment by beckywallace** [comment]
But that's my whole point.  These were NOT failed starts so 1 - why does the system think they are failed, and 2 - why is payment information out there when no payment was included on the start?  These were starts via Mobile LTE for a billed offer.

**Comment by mkoza178** [comment]
The system doesn't think they are failed. The process that pulls the file is the one that makes the determination if it is a success or failure. In Prod, this file won't exist.

**Comment by mkoza178** [comment]
And the billed starts had a payment record because that's how the file was constructed. It's not dynamic to not show payment for billed offers.

**Comment by beckywallace** [comment]
Have to admit I don't have a warm and fuzzy about this one.  I'll want to be able to complete a billed start via SolCon without it appearing in any file that we receive.

**Comment by mkoza178** [comment]
Sure, I agree. A billed start should go through the circ api. 
I just don't want to spin our wheels on a file that won't be used going forward.

**Comment by beckywallace** [comment]
Sorry, I'm really not trying to be a pain on this.  It just concerns me that we see in SubCon an Edgil failure when there shouldn't have been an Edgil call on this???

**Comment by mkoza178** [comment]
I agree. It's a bug on how we are processing a billed offer. It should never fire an Edgil transaction. I have a ticket open to my team on this.

**Comment by mkoza178** [comment]
TFS 34573

**Comment by mkoza178** [comment]
Try now. See event id 578369.

It was submitted successfully to DTI.
