### ISSUE TITLE
NOLA - TPGracePayments file includes bogus data, and does not include expected payments

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#68]
See below for the file that was received for Grace Payments vs the Grace Payments that show in SubCon for yesterday (3/9).  All but one of the payments in the file are not even showing in SubCon?  Of what IS showing in SubCon, we only received a payment for subscriber 7011 - Susan Leblanc (last record).

SubCon:
![image](https://cloud.githubusercontent.com/assets/25667903/23798205/2423cee2-0569-11e7-8620-a1952ac78855.png)

File:
![image](https://cloud.githubusercontent.com/assets/25667903/23798227/3ffe4804-0569-11e7-98b1-d75addbb317b.png)

**Comment by mkoza178** [comment]
Becky, have a look at the 3/10 file. 
On 3/9 the devs process captured all the old/bad data. I would not look at that.

I looked at 3/10 file and I see the 4 GracePays from the prior day. Attaching that txt file.  
[TPGracePayments03102017.txt](https://github.com/mkoza178/Advance---MI-Merge/files/834531/TPGracePayments03102017.txt)
