### ISSUE TITLE
NOLA - Restart Payment in SolCon payment file

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#69]
A restart payment record is in the SolCon payment file.  Should be in the RSTPay file that is not present in the 3/10 files:
![image](https://cloud.githubusercontent.com/assets/25667903/23809538/a63503d6-0593-11e7-8a29-cc2a44f58611.png)

Files received for 3/10:

SubCon:
![image](https://cloud.githubusercontent.com/assets/25667903/23809529/9efe9b4a-0593-11e7-9181-1c18c40ad129.png)

Record in File:
![image](https://cloud.githubusercontent.com/assets/25667903/23809578/cafd7bf8-0593-11e7-9130-aee988815237.png)

**Comment by mkoza178** [comment]
I was not going to ask the developer to update this as it's not being changed in prod and I have a task, for after the MI merge, to have all these payment files be combined into one.
