### ISSUE TITLE
Can't Register AAN Subscriber

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#7]
I'm unable to register an Ann Arbor account
![aan_can t register account](https://cloud.githubusercontent.com/assets/25616655/22841597/345006d4-efa0-11e6-8887-2de143e796e6.png)

**Comment by mkoza178** [comment]
TFS 34309

**Comment by mkoza178** [comment]
Re-test! Should be good!

**Comment by apattok** [comment]
Resolved.
