### ISSUE TITLE
GRP - Easy Pay sign up Term length 

### ISSUE THREAD

**Issue by JLewis12** [mkoza178/Advance---MI-Merge#70]
I was able to enter Billing Changes to Easy Pay for both CC and ACH (Account 540254) but I believe the terms were incorrect.

ACH = 4 week
CC = 8 week

![image](https://cloud.githubusercontent.com/assets/26151269/23810241/9c55d83a-0585-11e7-8f55-1f235eb16568.png)

![image](https://cloud.githubusercontent.com/assets/26151269/23810258/a8f022a8-0585-11e7-9103-2867ec20e0e0.png)

I believe they should be 5 wk?

-JasonL

**Comment by JLewis12** [comment]
Found out the reason - It was the Term I selected from the list of amounts..

**Comment by mkoza178** [comment]
Confirmed, all is well.
