### ISSUE TITLE
Nola - Easy Pay signup error

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#72]
Today when trying to sign a subscriber up for Easy Pay, getting the following error displayed.  I've tried with two different subs (77243 and 265119)  who currently are not Easy Pay subscribers so there should be no error.

![image](https://cloud.githubusercontent.com/assets/25667903/23867935/96b3152e-07eb-11e7-9d04-060d739d9a42.png)

**Comment by mkoza178** [comment]
Hm. 

Can you try again with another sub. I was able to submit one. See event id 578390
