### ISSUE TITLE
TFS 34794 Nola - Error for Carrier Collect sub trying to enter vacation stop

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#73]
When a Carrier Collect sub (sub 65814) selects Vacation Request, receives the following error - should be able to enter vacation ?:

![image](https://cloud.githubusercontent.com/assets/25667903/23868448/6efb32f8-07ed-11e7-9e3e-af9913951f93.png)

**Comment by mkoza178** [comment]
TFS 34794

**Comment by apattok** [comment]
ready to test

**Comment by beckywallace** [comment]
Re-tested, able to enter a vacation stop.
