### ISSUE TITLE
TFS 34794 Nola - Carrier Collect sub unable to enter delivery issue

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#74]
Carrier Collect sub (65814) receives the following error when selecting Report a Delivery Issue:

![image](https://cloud.githubusercontent.com/assets/25667903/23868578/eaca8a64-07ed-11e7-8799-b1d1e4866afc.png)

**Comment by mkoza178** [comment]
TFS 34794

**Comment by apattok** [comment]
ready for testing

**Comment by beckywallace** [comment]
RETESTED, ABLE TO ENTER A COMPLAINT.
