### ISSUE TITLE
TFS 34812 - No radio buttons for payment terms on Make Payment or Change to Easy Pay page

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#75]
In production, there are radio buttons for each payment term both when making a payment (makepayment.aspx) and changing to Easy Pay (EZPay.aspx) which makes it clear a selection is to be made.  These radio buttons are missing in test:

**Production Make Payment**
![image](https://cloud.githubusercontent.com/assets/25667903/23913007/90e89df2-08af-11e7-8218-5447a6d58fdc.png)

**Production Easy Pay signup**
![image](https://cloud.githubusercontent.com/assets/25667903/23913037/a9de654e-08af-11e7-8e72-4d5788e93ecc.png)

**Test Make Payment**
![image](https://cloud.githubusercontent.com/assets/25667903/23913152/0eee869e-08b0-11e7-8534-97dae0216317.png)

**Test Easy Pay signup**
![image](https://cloud.githubusercontent.com/assets/25667903/23913182/1f9a6a9e-08b0-11e7-8f66-b1aec6e7d3bd.png)

**Comment by mkoza178** [comment]
TFS 34812

**Comment by beckywallace** [comment]
Radio buttons now appear on both pages:

Switch to EasyPay:
![image](https://cloud.githubusercontent.com/assets/25667903/24313069/65a1ae66-10a9-11e7-9c73-1184bef81b71.png)

Make Payment:
![image](https://cloud.githubusercontent.com/assets/25667903/24313079/743224ba-10a9-11e7-890a-bd47d1209b2a.png)
