### ISSUE TITLE
TFS 35016 Payment amount is $0.00 in RESTRTPAYMENTACH email

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#76]
In event ID 590779, an ACH payment was made for $3.76.  The email sent indicates $0.00:

![image](https://cloud.githubusercontent.com/assets/25667903/23951024/ee2a89ca-095a-11e7-9470-abfa42f3a5ca.png)

Event Type Email setup:
![image](https://cloud.githubusercontent.com/assets/25667903/23951036/fb3fee3e-095a-11e7-86d1-d03d8d7a05d9.png)
![image](https://cloud.githubusercontent.com/assets/25667903/23951043/fe8463c2-095a-11e7-8c9b-abf260a595ac.png)

**Comment by mkoza178** [comment]
Excellent catch. This is actually correct email setup. The bug is in the code.

**Comment by apattok** [comment]
ready to test

**Comment by beckywallace** [comment]
Email is still showing amount of $0.00 for ACH Payment (event type 617).  For CC payment restart (event type 618), no email is being generated.

Email for event type 617:
![image](https://cloud.githubusercontent.com/assets/25667903/24313700/1157155a-10ac-11e7-9b3a-6b14f14ce452.png)

**Comment by mkoza178** [comment]
Email sent with zip file of DNR and Restart files to Becky and Amanda for them to load.

**Comment by mkoza178** [comment]
This should be good to go. Re-test, please.

**Comment by beckywallace** [comment]
Marc - still getting $0.00 for the payment amount in the email:

![image](https://cloud.githubusercontent.com/assets/25667903/24513154/1d4a7f76-1536-11e7-92ad-f88d26e4a40d.png)

![image](https://cloud.githubusercontent.com/assets/25667903/24513170/2921eda2-1536-11e7-813b-668d54d266a7.png)

**Comment by mkoza178** [comment]
Hey guys,

I tried a test today. Looks good in the email. Give it a go.

**Comment by beckywallace** [comment]
email looked good yesterday, I'm going to see if the files are good this morning!

**Comment by beckywallace** [comment]
email and file now both reflect the correct payment amount.
