### ISSUE TITLE
TFS 34835 Both Payment & EZ Pay workflows should display terms lowest to highest

### ISSUE THREAD

**Issue by jvanzomeren** [mkoza178/Advance---MI-Merge#77]
Even within the same workflow / customer I see it presented differently

<img width="1175" alt="screen shot 2017-03-15 at 1 20 15 pm" src="https://cloud.githubusercontent.com/assets/25616598/23965880/d871b65a-098f-11e7-94cc-4f104104bdfe.png

**Comment by apattok** [comment]
Tested - both workflows show payments listed low to high.
