### ISSUE TITLE
TFS 34836 Notification () not found

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#78]
When attempting to switch to EasyPay for a subscriber who has made a payment today, the error is presented as follows:

![image](https://cloud.githubusercontent.com/assets/25667903/23966412/4582afbc-0989-11e7-9beb-97e359f0a3e7.png)

**Comment by apattok** [comment]
ready to test internal MG2, but we can test also

**Comment by beckywallace** [comment]
Now receiving correct error message (likely needs to be tweaked in CMS)

![image](https://cloud.githubusercontent.com/assets/25667903/24310604/92597de0-109e-11e7-9645-c23f35d9316b.png)
