### ISSUE TITLE
TFS 34838 Error on dssSubscribe when Submit clicked before Email verification

### ISSUE THREAD

**Issue by beckywallace** [mkoza178/Advance---MI-Merge#79]
On dssSubscribe, if an email address is entered and the user clicks Submit instead of Verify, they are given the following error, even though the user agreement is not yet visible (that is displayed after Verify is clicked):

![image](https://cloud.githubusercontent.com/assets/25667903/23967434/e6cd97b2-098c-11e7-9b70-b6d2f7590924.png)

**Comment by apattok** [comment]
ready to test per John P.

**Comment by beckywallace** [comment]
Re-tested - Submit button is now unavailable and only the Verify button is available.
