### ISSUE TITLE
Account Stopped?

### ISSUE THREAD

**Issue by LISAANN9266** [mkoza178/Advance---MI-Merge#8]
According to SubCon, account 2105851 is Stopped.  I attempted to register account and successfully did with lstarweconversion+gaz8@gmail.com

Attempted another stopped account (according to SubCon) and it also registered email.  Account #1218823

Can you check to see if these accounts are stopped in test.

**Comment by mkoza178** [comment]
Yes, they are both Stopped in Test.

**Comment by LISAANN9266** [comment]
I was able to activate membership on both of these accounts.  This is why I was a bit confused as to if I could tell if they were stopped.

I registered lstarkweconversion+gaz8@gmail.com to acct #2105851
and
I registered lstarkweconversion+gazb8@gmail.com to acct #1218823

I am guessing that I need to log this as an error?

**Comment by mkoza178** [comment]
Why? You should be able to register to Stopped accounts.

**Comment by LISAANN9266** [comment]
I guess I misunderstood then.  According to the DSSMatch, my expected results for registering an account that is stopped is an error message.  I was able to register both accounts and you stated that they are stopped.

**Comment by mkoza178** [comment]
I see, I'll clarify in the doc. They should be allowed to register.
