### ISSUE TITLE
Easy Pay Disclaimer on New Start

### ISSUE THREAD

**Issue by LISAANN9266** [mkoza178/Advance---MI-Merge#82]
Easy Pay disclaimer is not showing correctly when starting a new subscription.

![starteasypaydisclaimer](https://cloud.githubusercontent.com/assets/25617462/24162246/1b9d9a32-0e24-11e7-9c45-6d4d3fc88aab.PNG)

**Comment by mkoza178** [comment]
sent an email to the team - updates can be made in CMS.  we also saw the correct language on the page.

**Comment by mkoza178** [comment]
Hey Lisa,

Is this still an issue? I'm seeing the correct language in CMS.

**Comment by apattok** [comment]
tested - resolved.
