### ISSUE TITLE
Customer Service Hours

### ISSUE THREAD

**Issue by LISAANN9266** [mkoza178/Advance---MI-Merge#83]
Customer service hours are not standardized.

![hours](https://cloud.githubusercontent.com/assets/25617462/24168694/515af958-0e38-11e7-92e6-a50868ba0e0a.PNG)

**Comment by mkoza178** [comment]
Sent an email to the team- updates can be made in CMS.

**Comment by mkoza178** [comment]
Hey guys, need any further assistance here?

**Comment by apattok** [comment]
yes....can't find where to update. Need to review with you.

**Comment by LISAANN9266** [comment]
Jason had been looking at this too and he said there was something funny about this.  If I remember correctly, I heard him mention that the days that look funny (no am or pm) were showing as inactive and yet still showing hours.  Since I am not to savvy on this, I was not exactly sure what that meant.

**Comment by mkoza178** [comment]
Lisa, are we all set here?

**Comment by LISAANN9266** [comment]
Yes, I updated all of them last week.
