### ISSUE TITLE
Payment Confirmation Page - Positive Balance Showing

### ISSUE THREAD

**Issue by apattok** [mkoza178/Advance---MI-Merge#84]
Can we make it so outstanding balance only shows if it's a negative balance? This customer has $208 available on their account. If they stopped today, that would be their refund. If they see this in their payment confirmation, it's going to scare people...it scared me. LOL
![paymentconfirmationpage_positivebalance](https://cloud.githubusercontent.com/assets/25616655/24462139/3cb313a2-1471-11e7-815d-6b3e150b9a4f.png)

**Comment by mkoza178** [comment]
Amanda, I'm gonna close this one out since we have another GitHub to track the standardizing of the paymentconfirm page.
