### ISSUE TITLE
Share Subscription Error with email

### ISSUE THREAD

**Issue by LISAANN9266** [mkoza178/Advance---MI-Merge#9]
![shareerror](https://cloud.githubusercontent.com/assets/25617462/22903452/7c607298-f1ed-11e6-8df9-de4da3f7a0a2.PNG)

Knowing that we still have to change the content on the email, are we suppose to follow through to activate the invitation?  Error when attempting to accept invite.

**Comment by mkoza178** [comment]
Hey Lisa,

Which prop was this for? It went to AJC's site. So the email link was wrong.

**Comment by LISAANN9266** [comment]
GAZ

**Comment by mkoza178** [comment]
Updated the email. You can try again.

**Comment by LISAANN9266** [comment]
![shareerror2](https://cloud.githubusercontent.com/assets/25617462/22937651/02e22ece-f28e-11e6-8cfc-ba26183ad457.PNG)

Looks like the screen is not refreshing properly.  Logged in as: lstarkweconversion+gaz9@gmail.com/password1

Plus I cannot remove previous invites or invite others.

**Comment by mkoza178** [comment]
Try incognitio window. I logged in and not seeing any issue.

**Comment by LISAANN9266** [comment]
Grrr - I just love all these web browsers.

**Comment by LISAANN9266** [comment]
![shareerror3](https://cloud.githubusercontent.com/assets/25617462/22941256/a6ff9356-f299-11e6-8762-2fd8b32c35dd.PNG)

When attempting to remove a current member from the shared subscriptions, an error appears.

**Comment by mkoza178** [comment]
Yes, I have a TFS out for this. Can you create a specific issue for this. There's a few in here and want to make sure we're clear what the TFS is for.

**Comment by LISAANN9266** [comment]
Sure.
